apiVersion: v1
kind: Service
metadata:
  name: zf-compressor-services
  namespace: prd
  labels:
    app: zf-compressor-services
spec:
  type: NodePort
  ports:
  - nodePort: 32032
    port: 32032
    protocol: TCP
    targetPort: 8087
  selector:
    app: zf-compressor-services
status:
  loadBalancer: {}

